### ISSUE TITLE
Need surveymonkey emails to come from different email address

### ISSUE THREAD

**Issue by jshermancody** [developmentseed/api.work.vote#60]
These are coming from our old address: info@fairelectionsnetwork.com

They should be coming from our new address: info@fairelectionscenter.org

**Comment by alyssadelaine** [comment]
@jshermancody This should be fixed; is it still happening?

**Comment by jshermancody** [comment]
@alyssadelaine It's still coming from info@fairelectionsnetwork.com unfortunately.

**Comment by alyssadelaine** [comment]
@jshermancody Okay, I just tried something else; would you mind checking again?

**Comment by alyssadelaine** [comment]
@jshermancody I believe this has been resolved, in which case I will close this issue. Please feel free to reopen if I am mistaken and this needs another look.
